[manager]
hovered         = { bg = "#161b22", bold = true }
selection       = { bg = "#1f6feb", bold = true }

[filetype]
rules = [
    { mime = "directory", fg = "#58a6ff", bold = true },
    { mime = "audio/*",   fg = "#484f58" },
    { mime = "video/*",   fg = "#484f58" },
    { mime = "image/*",   fg = "#76e3ea" },
    
    { name = "*.fish", mime = "*", fg = "#58a6ff" },
    { name = "*.lua",  mime = "*", fg = "#bc8cff" },
    { name = "*.rs",   mime = "*", fg = "#ffa198" },
    { name = "*.go",   mime = "*", fg = "#76e3ea" },
    { name = "*.js,*.ts", mime = "*", fg = "#d29922" },
    { name = "*.py",   mime = "*", fg = "#3fb950" },
]
