[plugin]
preload_max_width = 5000
preload_max_height = 5000

[manager]
show_hidden = true
show_mtime = true
linemode = "size"
sort_by = "alphabetical"
sort_sensitive = false

[status]
show_perm = false
show_owner = false
show_group = false

[preview]
image_quality = 75
max_width = 800
max_height = 800
