# Main background, empty for terminal default, black for 24-bit black
theme[main_bg]="#0a0a0a"

# Main text color
theme[main_fg]="#00ffff"

# Title color for boxes
theme[title]="#00ffff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ffffff"

# Background color of selected item in processes box
theme[selected_bg]="#005f5f"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#005f5f"

# Color of text appearing on top of graphs, i.e. uptime and current network graph scaling
theme[graph_text]="#00ffff"

# Background color of the percentage meters
theme[meter_bg]="#005f5f"

# Misc colors for lines and boxes
theme[proc_misc]="#00ffff"

# Cpu box outline color
theme[cpu_box]="#00ffff"

# Memory box outline color
theme[mem_box]="#00ffff"

# Net box outline color
theme[net_box]="#00ffff"

# Processes box outline color
theme[proc_box]="#00ffff"

# Box divider line and small boxes line color
theme[div_line]="#008080"

# Temperature graph colors
theme[temp_start]="#00ffff"
theme[temp_mid]="#00d7d7"
theme[temp_end]="#008080"

# CPU graph colors
theme[cpu_start]="#00ffff"
theme[cpu_mid]="#00d7d7"
theme[cpu_end]="#008080"

# Mem graph colors
theme[free_start]="#008080"
theme[free_mid]="#00d7d7"
theme[free_end]="#00ffff"

# Net graph colors
theme[download_start]="#00ffff"
theme[download_mid]="#00d7d7"
theme[download_end]="#008080"

theme[upload_start]="#00ffff"
theme[upload_mid]="#00d7d7"
theme[upload_end]="#008080"

# Process view background color of the parent of the selected process
theme[process_start]="#00ffff"
theme[process_mid]="#00d7d7"
theme[process_end]="#008080"
